Docker development environment for simple testing
meeting-room-booking-system/mrbs-code pull request #2
Opened 2021-08-01 14:26 UTC by being-peace

I added a docker environment, such that you can simply set up a test environment on Linux or Windows Docker with

  cd example
  docker-compose up -d

See also: https://sourceforge.net/p/mrbs/patches/111/

2021-08-02 07:38 UTC, pa-jberanek requested changes
Thanks for this - looks good apart from the typo I spotted. For interest I took your idea and ran with it to generate Kubernetes config, an alternative to Docker Compose.

2021-08-02 07:38 UTC, pa-jberanek commented on docker_app/HOWTO.md
> +* Delete persited volumes:
A small typo here, pesited -> persisted

2021-08-02 07:40 UTC, jberanek commented
Apologies, this review was meant to be from my personal GitHub account...

2021-08-02 20:54 UTC, merged

2021-08-03 09:23 UTC, being-peace commented
> Thanks for this - looks good apart from the typo I spotted. 
@jberanek  Thanks!

> For interest I took your idea and ran with it to generate Kubernetes config, an alternative to Docker Compose.
I must admit that I am rather new to this container thing. The docker files gives me a super easy development environment on Windows and Linux. I don´t know, what is the advantage of a Kubernetes config.

Is there anything you could commit here?

2021-08-06 15:17 UTC, jberanek commented
So, this is where I'm not convinced - Kubernetes would arguably be a better way to deploy MRBS in production, but realistically how many MRBS installers would have a Kubernetes cluster available, or would build one to host MRBS...?

2021-08-06 15:22 UTC, jberanek commented
The in-progress k8s config I built https://github.com/jberanek/mrbs-k8s

2021-08-07 14:33 UTC, being-peace commented
Ok, thanks. Could you describe, what you gain from this? Do I get it right: if you have a k8s Environment you can easily start mrbs for development purposes there. For productive systems there is manual work to do because of the fixed passwords…?

> 
> Am 06.08.2021 um 17:22 schrieb jberanek ***@***.***>:
> 
> ﻿
> The in-progress k8s config I built https://github.com/jberanek/mrbs-k8s
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> Triage notifications on the go with GitHub Mobile for iOS or Android.